### PR TITLE
Remove references to sensor_msgs::PointCloud

### PR DESCRIPTION
**Pull request by f-fl0**
It does not look like the use of `sensor_msgs::PointCloud` is necessary. For consistency, using `sensor_msgs::PointCloud2` seems better.

### CODE REVIEW

**Comment by f-fl0** [comment]
@at-wat any idea why this happened? https://travis-ci.org/github/at-wat/mcl_3dl/jobs/716918432#L3455

**Comment by at-wat** [comment]
It's a bug in the latest version in gh-pr-comment. I'm going to fix it.

**Comment by f-fl0** [comment]
> It's a bug in the latest version in gh-pr-comment. I'm going to fix it.

No rush. Thanks!. Let me know if there is anything I can help with.

**Comment by at-wat** [comment]
## [[#833](https://travis-ci.org/at-wat/mcl_3dl/builds/716918428)] PASSED on noetic

Tested on Alpine ROS

**Pull request merged**
